apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: tikceto-secrets
  namespace: tikceto
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: tikceto-secrets
    creationPolicy: Owner
  dataFrom:
    - key: tikceto