apiVersion: v1
kind: ServiceAccount
metadata:
  name: tikceto-eso-sa
  namespace: tikceto
---
apiVersion:  external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: tikceto
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "tikceto-eso-role" 
          serviceAccountRef:
            name: "tikceto-eso-sa"
            audiences:
              - vault