apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 69.3.1
    releaseName: monitoring
    namespace: monitoring
    valuesInline:
      prometheusOperator:
        admissionWebhooks:
          enabled: false
      grafana:
        enabled: true

patches:
  - target:
      kind: Deployment
      name: monitoring-kube-prometheus-operator
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/0
      - op: remove
        path: /spec/template/spec/volumes/0
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: 
          - --kubelet-service=kube-system/monitoring-kube-prometheus-kubelet
          - --web.listen-address=:10250