prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: "512Mi"
      limits:
        memory: "2Gi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
grafana:
  enabled: true
  ingress:
    enabled: false 

alertmanager:
  enabled: true
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true