# For the experiment using tailscale outside of cluster
# apiVersion: v1
# kind: Service
# metadata:
#   name: ts-k8s-api
#   namespace: default
#   annotations:
#     tailscale.com/expose: "true"
#     tailscale.com/hostname: "k3s-api"
# spec:
#   type: ExternalName
#   externalName: kubernetes.default.svc.cluster.local
#   ports:
#   - name: https
#     port: 443
#     targetPort: 443
