apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tg-bot
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: operator-oauth 
    creationPolicy: Owner
  data:
  - secretKey: bot_token
    remoteRef:
      key: tg-bot
      property: bot_token
