apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.0
    helm:
      values: |
        deploymentMode: Monolithic
        gateway:
          enabled: false
        minio:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              chunks-cache: chunks-cache
              results-cache: results-cache
          
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          
          pattern_ingester: { enabled: true }
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          ruler:
            enable_api: true
          storage_config:
            aws: null

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: "local-path"
            size: 20Gi
        backend: { replicas: 0 }
        read: { replicas: 0 }
        write: { replicas: 0 }
        ingester: { replicas: 0 }
        querier: { replicas: 0 }
        queryFrontend: { replicas: 0 }
        queryScheduler: { replicas: 0 }
        distributor: { replicas: 0 }
        compactor: { replicas: 0 }
        indexGateway: { replicas: 0 }
        bloomPlanner: { replicas: 0 }
        bloomBuilder: { replicas: 0 }
        bloomGateway: { replicas: 0 }

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6
    helm:
      values: |
        config:
          clients:
            - url: http://grafana-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]