apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            size: 5Gi

        promtail:
          enabled: true

        grafana:
          enabled: true


        prometheus:
          enabled: true
          server:
            retention: 3d
            persistentVolume:
              size: 5Gi
          alertmanager:
            enabled: false
          nodeExporter:
            enabled: true
          kubeStateMetrics:
            enabled: true

        fluent-bit:
          enabled: false
        filebeat:
          enabled: false
        logstash:
          enabled: false
  destination:
    name     : in-cluster
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true